languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "Shriveling world"
theme = "techdoc"
relativeURLs = "true"
[[menu.main]]
    name = "User documentation" #Name in the navigation bar
    weight = 10 #The larger the weight, the more on the right this item will be
    url = "/" #URL address
[[menu.main]]
    name = "Developper documentation"
    weight = 20
    url = "/documentation/"
[[menu.main]]
    name = "Application"
    weight = 30
    url = "/app/"
